import type { ThemeDefinition, ThemeExtensionTokenName } from "../types";

const auspexVar = (name: ThemeExtensionTokenName) => `var(--${name})`;

const auspexExtensionVariables = {
  void: "#08090F",
  "void-2": "#0B0D16",
  "void-3": "#0E1019",
  hull: "#12131D",
  "hull-2": "#161826",
  "hull-3": "#1B1D2B",
  panel: "rgba(20,22,34,.62)",
  "panel-2": "#161826",
  "panel-solid": "#12131D",
  hair: "rgba(150,156,190,.13)",
  "hair-2": "rgba(155,162,196,.24)",
  "hair-3": "rgba(170,176,210,.40)",
  line: "rgba(150,156,190,.16)",
  "line-2": "rgba(170,176,210,.30)",
  ink: "#E7E9F3",
  "ink-2": "#AEB2C8",
  "ink-3": "#6E7290",
  "ink-4": "#494D66",
  lilac: "#A7A9EC",
  "lilac-hi": "#C7C8F6",
  "lilac-deep": "#6F72C9",
  amber: "#E2B266",
  "amber-deep": "#B98A38",
  steel: "#82B2D0",
  "steel-soft": "#A6CEE6",
  jade: "#6FC79A",
  coral: "#E08A8A",
  "coral-deep": "#C46A6A",
  "glow-lilac": "rgba(167,169,236,.35)",
  "glow-amber": "rgba(226,178,102,.30)",
  bevel:
    "inset 0 1px 0 rgba(190,196,235,.10), inset 0 0 0 1px rgba(255,255,255,.012)",
  "orb-fill":
    "conic-gradient(from 220deg, #8E7BE6, #C77BD0, #E2A85C, #5FC9C0, #8E7BE6)",
  "orb-shadow": "0 0 22px var(--glow-lilac)",
  "orb-shadow-think":
    "0 0 30px var(--glow-lilac), 0 0 54px rgba(199,123,208,.25)",
  "bezel-fill":
    "linear-gradient(150deg, rgba(216,220,242,.92), rgba(120,125,152,.22) 40%, rgba(58,61,80,.35) 60%, rgba(176,181,206,.72))",
  "bezel-fallback-ring": "var(--line-2)",
  "focus-ring-width": "2px",
  "focus-ring-offset": "2px",
  "focus-ring-shadow": "0 0 0 4px var(--glow-lilac)",
  "glass-blur": "16px",
  "glass-shadow": "0 10px 30px rgba(0,0,0,.28)",
  "r-sm": "7px",
  "r-md": "11px",
  "r-lg": "14px",
  disp: 'var(--font-saira), "Saira", system-ui, sans-serif',
  head: 'var(--font-michroma), "Michroma", "Microgramma", system-ui, sans-serif',
  mono: 'var(--font-jetbrains-mono), "JetBrains Mono", ui-monospace, monospace',
  body: 'var(--font-inter), "Inter", system-ui, sans-serif',
} as const satisfies Record<ThemeExtensionTokenName, string>;

export const auspexTheme = {
  id: "auspex",
  label: "AUSPEX",
  mode: "dark",
  colorScheme: "dark",
  colorPrimitives: {
    "ink-950": auspexExtensionVariables.void,
    "ink-900": auspexExtensionVariables.hull,
    "ink-850": auspexExtensionVariables["hull-2"],
    "ink-700": auspexExtensionVariables["hull-3"],
    "ink-300": auspexExtensionVariables["ink-2"],
    "field-500": auspexExtensionVariables.lilac,
    "field-950": auspexExtensionVariables.void,
    "win-500": auspexExtensionVariables.jade,
    "loss-500": auspexExtensionVariables.coral,
    "flag-500": auspexExtensionVariables.amber,
    "live-500": auspexExtensionVariables.lilac,
    hairline: auspexExtensionVariables.line,
    "focus-ring": auspexExtensionVariables.lilac,
  },
  colorAliases: {
    background: auspexVar("void"),
    foreground: auspexVar("ink"),
    surface: auspexVar("panel-solid"),
    elevated: auspexVar("hull-2"),
    card: "var(--surface)",
    "card-foreground": "var(--foreground)",
    popover: "var(--elevated)",
    "popover-foreground": "var(--foreground)",
    primary: auspexVar("lilac"),
    "primary-foreground": auspexVar("void"),
    secondary: "var(--elevated)",
    "secondary-foreground": "var(--foreground)",
    muted: "var(--surface)",
    "muted-foreground": auspexVar("ink-2"),
    accent: "var(--elevated)",
    "accent-foreground": "var(--foreground)",
    destructive: "var(--negative)",
    positive: auspexVar("jade"),
    negative: auspexVar("coral"),
    warning: auspexVar("amber"),
    highlight: auspexVar("lilac"),
    border: auspexVar("line"),
    input: auspexVar("hair-2"),
    ring: auspexVar("lilac"),
    "chart-1": auspexVar("lilac"),
    "chart-2": auspexVar("amber"),
    "chart-3": auspexVar("steel"),
    "chart-4": auspexVar("jade"),
    "chart-5": auspexVar("coral"),
    sidebar: auspexVar("hull"),
    "sidebar-foreground": auspexVar("ink"),
    "sidebar-primary": auspexVar("lilac"),
    "sidebar-primary-foreground": auspexVar("void"),
    "sidebar-accent": auspexVar("hull-2"),
    "sidebar-accent-foreground": auspexVar("ink"),
    "sidebar-border": auspexVar("line"),
    "sidebar-ring": auspexVar("lilac"),
  },
  type: {
    "font-family-heading": auspexVar("head"),
    "font-family-display": auspexVar("disp"),
    "font-family-sans": auspexVar("body"),
    "font-family-body": auspexVar("body"),
    "font-family-mono": auspexVar("mono"),
    "font-family-editorial": auspexVar("disp"),
    "type-size-xs": "0.6875rem",
    "type-line-xs": "1.4",
    "type-size-sm": "0.8125rem",
    "type-line-sm": "1.5",
    "type-size-base": "0.875rem",
    "type-line-base": "1.5",
    "type-size-lg": "1.25rem",
    "type-line-lg": "1.3",
    "type-size-xl": "1.3125rem",
    "type-line-xl": "1.1",
    "type-size-2xl": "1.75rem",
    "type-line-2xl": "1.05",
    "type-size-3xl": "2.625rem",
    "type-line-3xl": "1",
    "type-size-xl-mobile": "1.1875rem",
    "type-size-2xl-mobile": "1.5rem",
    "type-size-3xl-mobile": "2.25rem",
    "numeric-figure-spacing": "tabular-nums",
    "heading-letter-spacing": "0.015em",
    "display-letter-spacing": "0.06em",
    "eyebrow-letter-spacing": "0.26em",
    "heading-clip-fill":
      "linear-gradient(180deg, #ffffff 52%, var(--lilac-hi) 145%)",
    "prose-size": "1.0625rem",
    "prose-size-wide": "1.1875rem",
    "prose-line": "1.65",
    "prose-line-wide": "1.75",
    "prose-measure": "70ch",
    "prose-paragraph-spacing": "1em",
    "prose-pullquote-size": "1.5rem",
    "lcd-value-shadow": "0 0 16px var(--glow-amber)",
    "lcd-live-shadow": "0 0 16px var(--glow-lilac)",
  },
  space: {
    "space-1": "0.25rem",
    "space-2": "0.5rem",
    "space-3": "0.75rem",
    "space-4": "1rem",
    "space-6": "1.5rem",
    "space-8": "2rem",
    "space-12": "3rem",
  },
  radius: {
    radius: auspexVar("r-md"),
    "radius-control": auspexVar("r-sm"),
    "radius-card": auspexVar("r-lg"),
    "radius-sheet": "16px",
    "control-radius": "var(--radius-control)",
    "card-radius": "var(--radius-card)",
    "sheet-radius": "var(--radius-sheet)",
  },
  elevation: {
    "shadow-flat": "none",
    "shadow-raised": "0 1px 2px rgba(0,0,0,.28), 0 12px 32px rgba(0,0,0,.22)",
    "shadow-overlay": "0 1px 2px rgba(0,0,0,.34), 0 22px 54px rgba(0,0,0,.34)",
    "elevation-flat": "var(--shadow-flat)",
    "elevation-raised": "var(--shadow-raised)",
    "elevation-overlay": "var(--shadow-overlay)",
  },
  motion: {
    "duration-fast": "150ms",
    "duration-base": "220ms",
    "duration-slow": "420ms",
    "duration-orb": "7000ms",
    "duration-atmosphere": "64000ms",
    "duration-count-up": "220ms",
    "duration-draw-in": "420ms",
    "duration-staged-process": "220ms",
    "duration-hover-lift": "150ms",
    "duration-focus-bloom": "150ms",
    "duration-marquee": "36000ms",
    "motion-duration-fast": "var(--duration-fast)",
    "motion-duration-base": "var(--duration-base)",
    "motion-duration-slow": "var(--duration-slow)",
    "motion-duration-orb": "var(--duration-orb)",
    "motion-duration-atmosphere": "var(--duration-atmosphere)",
    "motion-duration-count-up": "var(--duration-count-up)",
    "motion-duration-draw-in": "var(--duration-draw-in)",
    "motion-duration-staged-process": "var(--duration-staged-process)",
    "motion-duration-hover-lift": "var(--duration-hover-lift)",
    "motion-duration-focus-bloom": "var(--duration-focus-bloom)",
    "motion-duration-marquee": "var(--duration-marquee)",
    "ease-out": "cubic-bezier(0.22, 1, 0.36, 1)",
    "ease-spring": "cubic-bezier(0.2, 0.9, 0.18, 1)",
    "ease-linear": "linear",
    "motion-ease-out": "var(--ease-out)",
    "motion-ease-spring": "var(--ease-spring)",
    "motion-ease-linear": "var(--ease-linear)",
  },
  extensionVariables: auspexExtensionVariables,
} as const satisfies ThemeDefinition;
