import type { ThemeDefinition } from "../types";

const primitiveColor = (name: string) => `var(--primitive-color-${name})`;

export const neutralDarkTheme = {
  id: "neutral-dark",
  label: "Neutral Dark",
  mode: "dark",
  colorScheme: "dark",
  colorPrimitives: {
    "ink-950": "oklch(16% 0.01 250)",
    "ink-900": "oklch(21% 0.012 250)",
    "ink-850": "oklch(25% 0.014 250)",
    "ink-700": "oklch(30% 0.012 250)",
    "ink-300": "oklch(72% 0.015 250)",
    "field-500": "oklch(72% 0.15 145)",
    "field-950": "oklch(18% 0.02 145)",
    "win-500": "oklch(75% 0.16 150)",
    "loss-500": "oklch(64% 0.2 25)",
    "flag-500": "oklch(80% 0.14 85)",
    "live-500": "oklch(78% 0.13 60)",
    hairline: "oklch(30% 0.012 250)",
    "focus-ring": "oklch(72% 0.15 145 / 60%)",
  },
  colorAliases: {
    background: primitiveColor("ink-950"),
    foreground: "oklch(96% 0.01 250)",
    surface: primitiveColor("ink-900"),
    elevated: primitiveColor("ink-850"),
    card: "var(--surface)",
    "card-foreground": "var(--foreground)",
    popover: "var(--elevated)",
    "popover-foreground": "var(--foreground)",
    primary: primitiveColor("field-500"),
    "primary-foreground": primitiveColor("field-950"),
    secondary: "var(--elevated)",
    "secondary-foreground": "var(--foreground)",
    muted: "var(--surface)",
    "muted-foreground": primitiveColor("ink-300"),
    accent: "var(--elevated)",
    "accent-foreground": "var(--foreground)",
    destructive: "var(--negative)",
    positive: primitiveColor("win-500"),
    negative: primitiveColor("loss-500"),
    warning: primitiveColor("flag-500"),
    highlight: primitiveColor("live-500"),
    border: primitiveColor("hairline"),
    input: primitiveColor("hairline"),
    ring: primitiveColor("focus-ring"),
    "chart-1": "var(--primary)",
    "chart-2": "var(--highlight)",
    "chart-3": "var(--warning)",
    "chart-4": "var(--negative)",
    "chart-5": "var(--muted-foreground)",
    sidebar: "var(--surface)",
    "sidebar-foreground": "var(--foreground)",
    "sidebar-primary": "var(--primary)",
    "sidebar-primary-foreground": "var(--primary-foreground)",
    "sidebar-accent": "var(--elevated)",
    "sidebar-accent-foreground": "var(--foreground)",
    "sidebar-border": "var(--border)",
    "sidebar-ring": "var(--ring)",
  },
  type: {
    "font-family-heading": 'var(--font-inter), "Inter", system-ui, sans-serif',
    "font-family-display": 'var(--font-inter), "Inter", system-ui, sans-serif',
    "font-family-sans": 'var(--font-inter), "Inter", system-ui, sans-serif',
    "font-family-body": 'var(--font-inter), "Inter", system-ui, sans-serif',
    "font-family-mono":
      'var(--font-jetbrains-mono), "JetBrains Mono", ui-monospace, monospace',
    "font-family-editorial":
      'var(--font-inter), "Inter", system-ui, sans-serif',
    "type-size-xs": "0.75rem",
    "type-line-xs": "1.35",
    "type-size-sm": "0.875rem",
    "type-line-sm": "1.45",
    "type-size-base": "1rem",
    "type-line-base": "1.5",
    "type-size-lg": "1.25rem",
    "type-line-lg": "1.4",
    "type-size-xl": "1.75rem",
    "type-line-xl": "1.25",
    "type-size-2xl": "2.5rem",
    "type-line-2xl": "1.1",
    "type-size-3xl": "3.25rem",
    "type-line-3xl": "1.05",
    "type-size-xl-mobile": "1.5rem",
    "type-size-2xl-mobile": "2rem",
    "type-size-3xl-mobile": "2.5rem",
    "numeric-figure-spacing": "tabular-nums",
    "heading-letter-spacing": "0",
    "display-letter-spacing": "0",
    "eyebrow-letter-spacing": "0",
    "heading-clip-fill":
      "linear-gradient(180deg, var(--foreground), var(--primary))",
    "prose-size": "1.0625rem",
    "prose-size-wide": "1.1875rem",
    "prose-line": "1.65",
    "prose-line-wide": "1.75",
    "prose-measure": "70ch",
    "prose-paragraph-spacing": "1em",
    "prose-pullquote-size": "1.5rem",
    "lcd-value-shadow": "none",
    "lcd-live-shadow": "none",
  },
  space: {
    "space-1": "0.25rem",
    "space-2": "0.5rem",
    "space-3": "0.75rem",
    "space-4": "1rem",
    "space-6": "1.5rem",
    "space-8": "2rem",
    "space-12": "3rem",
  },
  radius: {
    radius: "0.625rem",
    "radius-control": "0.375rem",
    "radius-card": "0.625rem",
    "radius-sheet": "1rem",
    "control-radius": "var(--radius-control)",
    "card-radius": "var(--radius-card)",
    "sheet-radius": "var(--radius-sheet)",
  },
  elevation: {
    "shadow-flat": "none",
    "shadow-raised":
      "0 1px 2px oklch(0% 0 0 / 24%), 0 8px 24px oklch(0% 0 0 / 18%)",
    "shadow-overlay":
      "0 1px 2px oklch(0% 0 0 / 28%), 0 18px 42px oklch(0% 0 0 / 26%)",
    "elevation-flat": "var(--shadow-flat)",
    "elevation-raised": "var(--shadow-raised)",
    "elevation-overlay": "var(--shadow-overlay)",
  },
  motion: {
    "duration-fast": "150ms",
    "duration-base": "220ms",
    "duration-slow": "320ms",
    "motion-duration-fast": "var(--duration-fast)",
    "motion-duration-base": "var(--duration-base)",
    "motion-duration-slow": "var(--duration-slow)",
    "ease-out": "cubic-bezier(0.22, 1, 0.36, 1)",
    "motion-ease-out": "var(--ease-out)",
  },
} as const satisfies ThemeDefinition;
