import type { ThemeDefinition } from "../types";
import { neutralDarkTheme } from "./neutral-dark";

const primitiveColor = (name: string) => `var(--primitive-color-${name})`;

export const neutralLightTheme = {
  ...neutralDarkTheme,
  id: "neutral-light",
  label: "Neutral Light",
  mode: "light",
  colorScheme: "light",
  colorPrimitives: {
    "ink-950": "oklch(98% 0.006 250)",
    "ink-900": "oklch(94% 0.008 250)",
    "ink-850": "oklch(90% 0.01 250)",
    "ink-700": "oklch(82% 0.012 250)",
    "ink-300": "oklch(42% 0.014 250)",
    "field-500": "oklch(44% 0.14 145)",
    "field-950": "oklch(98% 0.008 145)",
    "win-500": "oklch(42% 0.13 150)",
    "loss-500": "oklch(47% 0.18 25)",
    "flag-500": "oklch(45% 0.12 85)",
    "live-500": "oklch(45% 0.11 60)",
    hairline: "oklch(82% 0.012 250)",
    "focus-ring": "oklch(44% 0.14 145 / 55%)",
  },
  colorAliases: {
    background: primitiveColor("ink-950"),
    foreground: "oklch(18% 0.01 250)",
    surface: primitiveColor("ink-900"),
    elevated: primitiveColor("ink-850"),
    card: "var(--surface)",
    "card-foreground": "var(--foreground)",
    popover: "var(--elevated)",
    "popover-foreground": "var(--foreground)",
    primary: primitiveColor("field-500"),
    "primary-foreground": primitiveColor("field-950"),
    secondary: "var(--elevated)",
    "secondary-foreground": "var(--foreground)",
    muted: "var(--surface)",
    "muted-foreground": primitiveColor("ink-300"),
    accent: "var(--elevated)",
    "accent-foreground": "var(--foreground)",
    destructive: "var(--negative)",
    positive: primitiveColor("win-500"),
    negative: primitiveColor("loss-500"),
    warning: primitiveColor("flag-500"),
    highlight: primitiveColor("live-500"),
    border: primitiveColor("hairline"),
    input: primitiveColor("hairline"),
    ring: primitiveColor("focus-ring"),
    "chart-1": "var(--primary)",
    "chart-2": "var(--highlight)",
    "chart-3": "var(--warning)",
    "chart-4": "var(--negative)",
    "chart-5": "var(--muted-foreground)",
    sidebar: "var(--surface)",
    "sidebar-foreground": "var(--foreground)",
    "sidebar-primary": "var(--primary)",
    "sidebar-primary-foreground": "var(--primary-foreground)",
    "sidebar-accent": "var(--elevated)",
    "sidebar-accent-foreground": "var(--foreground)",
    "sidebar-border": "var(--border)",
    "sidebar-ring": "var(--ring)",
  },
} as const satisfies ThemeDefinition;
